### ISSUE TITLE
[BUG] Alignment when opening next to buffer with lines exceeding visible columns

### ISSUE THREAD

**Issue by lcrockett** [sidebar-nvim/sidebar.nvim#11]
If a buffer is opened in a window that does not exceed the visible column length of the screen, and then you open sidebar, all is well. Once you open sidebar while having a buffer opened that has lines exceeding the visible column length of the screen, sidebar also shifts it's initial position to the right. You'll have to manually focus on the sidebar panel to align it to the left, as one would expect it aligns initially. See video below for a demonstration of the bug and currently used configuration.

```lua
require('sidebar-nvim').setup {
  bindings = {
    ['q'] = function()
      require('sidebar-nvim').close()
    end
  },
  disable_default_keybindings = 0,
  ["git-status"] = {
    icon = "",
  },
  initial_width = 50,
  section_separator = '',
  sections = {'git-status', 'lsp-diagnostics', 'todos'},
  todos = {
    initially_closed = true
  },
  update_interval = 250
}
```

https://user-images.githubusercontent.com/58056722/138563477-2233f8f6-9c72-4e8c-a07e-abf0c5e4aa9e.mov

**Comment by GustavoKatel** [comment]
hi @lcrockett can u confirm that this bug is still happening in with the most recent commits (`main` or `dev`)? TIA

**Comment by lcrockett** [comment]
The bug did appear again around the time of updating to the latest `main`, just not entirely sure if it was before or after the latest pull of changes. Let's close this one and have it re-opened if it does appear again in a reproducible manner.
