### ISSUE TITLE
[Feature request] Update diagnostics at InsertLeave

### ISSUE THREAD

**Issue by lcrockett** [sidebar-nvim/sidebar.nvim#15]
Diagnostics are currently updated in real-time, which is great, except for cases when using `update_in_insert = false` (my personal default) in `vim.diagnostic.config`. Could we follow this value, or allow for a `sidebar.nvim` specific setting to control this behaviour ?

**Comment by GustavoKatel** [comment]
@lcrockett this should be resolved in https://github.com/sidebar-nvim/sidebar.nvim/commit/9569f6c4845f4e02758a7285a9dace1b29423fe7 we are now using the autocommand `DiagnosticChanged` which should respect your settings better.
