### ISSUE TITLE
[Bug] builtin files not work

### ISSUE THREAD

**Issue by aspeddro** [sidebar-nvim/sidebar.nvim#16]
Hi @GustavoKatel, i installed sidebar.nvim and run `:PackerCompiler`, however the files do not appear.

![image](https://user-images.githubusercontent.com/16160544/149637818-72576e18-84ad-417b-99ee-3ea089c02540.png)

```sh
nvim --version                 
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

Thanks for working on this plugin, it's really good!!!

**Comment by GustavoKatel** [comment]
Hi @aspeddro you need to enable it using the [sections option](https://github.com/sidebar-nvim/sidebar.nvim/blob/main/doc/general.md#sections).

For example:

```lua
require("sidebar-nvim").setup({
    sections = { "datetime", "git", "diagnostics", "files" },
})
```

**Comment by aspeddro** [comment]
Thank you
