### ISSUE TITLE
Keybindings inconstancy

### ISSUE THREAD

**Issue by paulrouget** [sidebar-nvim/sidebar.nvim#17]
In the File section, `Enter` will open the file under the cursor. In Buffer and Git, it's `e`.

**Comment by paulrouget** [comment]
Oh it actually works. But to open a folder, we need to use `Enter`.

**Comment by paulrouget** [comment]
Ideally, there would be on single key to both open a file, and unfold folders, at least for the Files section.

I love this project btw, it became my daily driver :)

**Comment by GustavoKatel** [comment]
yep! this is reasonable. we'll work on this. thanks!

**Comment by davysson** [comment]
This is fixed in `dev` with https://github.com/sidebar-nvim/sidebar.nvim/commit/43751e6030210cfce123314c161331c6885a59aa. Now `e` will both open files and toggle folders.
