### ISSUE TITLE
Add a binding to close buffer

### ISSUE THREAD

**Issue by paulrouget** [sidebar-nvim/sidebar.nvim#18]
It would be great if `d` could delete the buffer.

**Comment by GustavoKatel** [comment]
you mean in the `buffers` section?

**Comment by paulrouget** [comment]
Yes.

**Comment by GustavoKatel** [comment]
this was added in https://github.com/sidebar-nvim/sidebar.nvim/commit/6c80ae29d5467682604682156094a677ad45a77c

already in `dev`
