### ISSUE TITLE
Cannot show sidebar due to an error

### ISSUE THREAD

**Issue by khalidchawtany** [sidebar-nvim/sidebar.nvim#19]
I just installed this plugin and I get the following error. Note: I am using the neovim master branch.
```
E5108: Error executing lua ...e/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim/view.lua:50: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_is_valid'
        ...e/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim/view.lua:50: in function 'is_buf_valid'
        ...e/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim/view.lua:200: in function 'open'
        ...te/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim/lib.lua:82: in function 'open'
        ...te/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim/lib.lua:98: in function 'toggle'
        ...m/site/pack/packer/opt/sidebar.nvim/lua/sidebar-nvim.lua:76: in function 'toggle'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Comment by paulrouget** [comment]
Just double checking: did you add `require("sidebar-nvim").setup{}` in your vimrc?

**Comment by ranjithshegde** [comment]
I have the same issue and I do have `require("sidebar-nvim").setup{}` as described in README

**Comment by khalidchawtany** [comment]
Yup, it happens only when lazy loaded. However, even if not lazy loaded I get an error on start up. The first time the sidebar is shown is empty and then it works.

```
packer.nvim: Error running config for sidebar.nvim: [string "..."]:0: attempt to index upvalue '' (a nil value)

```

**Comment by GustavoKatel** [comment]
I just pushed a fix to the `dev` branch. Can you try and see if that works? thanks a lot

**Comment by ranjithshegde** [comment]
can confirm it works for me in dev branch! I can lazy load now with no issues
Thank you for the fix, and of course the wonderful plugin

**Comment by khalidchawtany** [comment]
Solves all my issues too.
