### ISSUE TITLE
Adjust section spacing

### ISSUE THREAD

**Issue by GustavoKatel** [sidebar-nvim/sidebar.nvim#25]
> Is it possible to adjust the spacing between sections (or between the section title and the section content)? There's too much whitespace for a small screen right now.

from: https://www.reddit.com/r/neovim/comments/s4s7ko/comment/hsus933/?utm_source=share&utm_medium=web2x&context=3

**Comment by davysson** [comment]
I pushed a commit to `dev` (https://github.com/sidebar-nvim/sidebar.nvim/commit/dffbec1b3f31a62b0bb53933f36f18d2b259b3a1) that should solve this issue, `section_separator` now also accept an array of strings as custom lines.

During the change I also noticed that we were adding an extra separator after the last section, that is now also fixed.
