### ISSUE TITLE
I can't configure the sidebar

### ISSUE THREAD

**Issue by linuxmobile** [sidebar-nvim/sidebar.nvim#27]
My sidebar, looks empty. I'm trying to settings it but i can't. I read the docs, but don't know.
![image](https://user-images.githubusercontent.com/10554636/149685688-097f6a1f-a74b-42c3-912e-41491bbddf55.png)

**Comment by linuxmobile** [comment]
> My sidebar, looks empty. I'm trying to settings it but i can't. I read the docs, but don't know. ![image](https://user-images.githubusercontent.com/10554636/149685688-097f6a1f-a74b-42c3-912e-41491bbddf55.png)

Another screenshot. 

![image](https://user-images.githubusercontent.com/10554636/149686282-fe093442-9bc8-44d1-af5c-6f5be2928a3f.png)

**Comment by Fymyte** [comment]
I think everything is [on this page](https://github.com/sidebar-nvim/sidebar.nvim/blob/main/doc/general.md).
If you want to configure the displayed `sections` you can add something like
```lua
require'sidebar-nvim'.setup {
  sections = { 'datetime', 'git', 'diagnostics', 'todos' },
}
```
That's what I use.
Every section listed on the given link can be added by appending its name to the `sections` list

**Comment by linuxmobile** [comment]
> ```lua
> sections = { 'datetime', 'git', 'diagnostics', 'todos
> ```

My settings looks like:

![image](https://user-images.githubusercontent.com/10554636/149688179-93521c1b-7053-4d57-bddf-facc793e717a.png)

**Comment by GustavoKatel** [comment]
@linuxmobile on your settings on line `9`, where it says `sections`, you need to add the sections that you want.

like @Fymyte said, you can use [these sections](https://github.com/sidebar-nvim/sidebar.nvim/blob/main/doc/builtin-sections.md). Just add the section name to the list in your config.

**Comment by linuxmobile** [comment]
> @linuxmobile on your settings on line `9`, where it says `sections`, you need to add the sections that you want.
> 
> like @Fymyte said, you can use [these sections](https://github.com/sidebar-nvim/sidebar.nvim/blob/main/doc/builtin-sections.md). Just add the section name to the list in your config.
> 
> if that does not work, you can share your dotfiles here and we can take a look.

You can found my dots [here](https://github.com/linuxmobile/dwm-dots)

**Comment by Fymyte** [comment]
What sections do you want to see in your sidebar?

**Comment by linuxmobile** [comment]
> What sections do you want to see in your sidebar?

I want to see **git status, diagnostic, files and todo.** 

I've got this settings, but files don't show. git don't show anything. And same with diagnostic

![image](https://user-images.githubusercontent.com/10554636/149749385-79ae40da-9483-4701-b991-7d2b9ca96b85.png)

**Comment by bpingris** [comment]
did you try with this simple settings:
```lua
local sidebar = require("sidebar-nvim")

sidebar.setup(
    {
        sections = {"files", "git", "diagnostics", "todos"}
    }
)
```
it keeps the default settings but overwrite the `sections` property, it works on my end

**Comment by linuxmobile** [comment]
> did you try with this simple settings:
> 
> ```lua
> local sidebar = require("sidebar-nvim")
> 
> sidebar.setup(
>     {
>         sections = {"files", "git", "diagnostics", "todos"}
>     }
> )
> ```
> 
> it keeps the default settings but overwrite the `sections` property, it works on my end

But where. I've got: nvi/lua/plugins/config/sidebar.nvim..  ( [check this screenshot](https://github.com/sidebar-nvim/sidebar.nvim/issues/27#issuecomment-1014344772) ).

And the init.lua [THIS](https://github.com/sidebar-nvim/sidebar.nvim/issues/27#issuecomment-1014036540)

**Comment by bpingris** [comment]
where you are already calling setup, remove all the options and start over with only this setting.
or, maybe you are missing some external dependencies 🤔

**Comment by linuxmobile** [comment]
> where you are already calling setup, remove all the options and start over with only this setting. or, maybe you are missing some external dependencies thinking

I do this many times but i've got the same result. Maybe i'm missing something. Can you check my dots in my profile? (repo is called `dwm-dots`)

**Comment by Fymyte** [comment]
I'm sorry @linuxmobile but I can't find where you require your `lua/plugin/config/sidebar.lua` (I think it's where I found it). You seems to have a rather complicated plugin management setup. Are you sure the file is required somewhere ?

**Comment by linuxmobile** [comment]
> I'm sorry @linuxmobile but I can't find where you require your `lua/plugin/config/sidebar.lua` (I think it's where I found it). You seems to have a rather complicated plugin management setup. Are you sure the file is required somewhere ?

I'm using packer.nvim to manage plugins. Then there's only few settings: nvim/lua/plugins/init.nvim (there's where I add the plugin to packer.nvim). Next to it, I compile with packer and the file under nvim/lua/plugins/configs/sidebar.nvim. that's all. I don't need more settings.

**Comment by Fymyte** [comment]
I might be wrong, but I see that for every plugin that have a custom config, you've added something like
```lua
config = override_req("nvim_web_devicons", "plugins.configs.icons")
```
in your packer config, but I don't see one for sidebar-nvim.
Shouldn't it has a line looking like that:
```lua
config = override_req("sidebar-nvim", "plugins.configs.sidebar-nvim")
```

**Comment by linuxmobile** [comment]
> I might be wrong, but I see that for every plugin that have a custom config, you've added something like
> 
> ```lua
> config = override_req("nvim_web_devicons", "plugins.configs.icons")
> ```
> 
> in your packer config, but I don't see one for sidebar-nvim. Shouldn't it has a line looking like that:
> 
> ```lua
> config = override_req("sidebar-nvim", "plugins.configs.sidebar-nvim")
> ```

Oh. I'm dumb. Thx you!!! that's i forget!!
