### ISSUE TITLE
[BUG] Sorting of items

### ISSUE THREAD

**Issue by lcrockett** [sidebar-nvim/sidebar.nvim#29]
It seems that, for instance, diagnostics and todos are not sorted explicitly. It would be nice if diagnostics would be sorted on a line > column basis. For TODOs it would be nice if it was sorted on filename first, then line number, then column number.

Optionally it would be nice to be able to control sorting of buffers. For instance based on their name, or buffer ID. The first makes more sense from a readability point of view.

At this point each time you toggle collapse on a TODO group the order changes of all TODO groups. It makes it harder to keep track of individual items you have fixated on visually.

If you're in need of more details, let me know.

**Comment by GustavoKatel** [comment]
you can now 

updated docs
this is in `dev` now, I'll merge to `main` by tomorrow

```
require("sidebar-nvim").setup({
    ...
    buffers = {
        icon = "",
        ignored_buffers = {}, -- ignore buffers by regex
        sorting = "id", -- alternatively set it to "name" to sort by buffer name instead of buf id
    }
    ...
})
```

**Comment by GustavoKatel** [comment]
@lcrockett I tried to find a lsp server that returned unsorted diagnostic entries, but without success. The ones I'm using are nicely sorted.

What server are you seeing unsorted diagnostics? can you also provide some screenshots if possible?

Also what nvim version are you using?

**Comment by lcrockett** [comment]
Cheers on the changes. I've tried them out and have a few pointers based on that:

* Buffer names seem to keep sorting on ID, even though I have `name` set for the sorting key (see used configuration and screenshot below)
* Sorting of TODO's are much better now, however I was still able to manage a sorting discrepancy when saving the buffer i'm currently in (see video below). Repeatedly saving (quickly) the buffer i'm currently in triggers the issue. During normal use of Neovim the issue is triggered every now and then when saving buffers or by triggering `SidebarNvimUpdate`
* I'll keep an eye on LSP sorting as for the time being I don't have a good example depicting the originally reported issue

A few unrelated points (let me know if you'd like separate issues for these)
* Would it be possible to make the open buffers listing configurable in order to be able to chop the buffer ID from the line showing in `sidebar-nvim` ? It's quite distracting when all you want to focus on is the filename of the buffer itself
* Would it be possible (potentially configurable) to indent the TODOs section with grouped filenames instead of showing the filename on the right of the TODO item ? Showing the filename on the right usually chops off the filename unless the `initial_width` is set to a IMO very high value. It would then go `TODO group -> Filename -> TODO item`, all centred on the left of the sidebar

I'm using Neovim 0.6.1, LuaJIT 2.0.5 @ Linux | MacOS Big Sur and the latest `sidebar.nvim` of branch `main`

<details>
  <summary>Sidebar configuration</summary>
  
```lua
require('sidebar-nvim').setup {
  bindings = {
    ['q'] = function()
      require('sidebar-nvim').close()
    end
  },
  buffers = {
    ignored_buffers = {
      'NvimTree',
      '-MINIMAP-',
      'neo-tree *',
      'zsh;#toggleterm*'
    },
    sorting = 'name'
  },
  disable_default_keybindings = 0,
  ["git-status"] = {
    icon = "",
  },
  files = {
    show_hidden = true
  },
  initial_width = 100,
  section_separator = '',
  sections = {
    'git',
    'diagnostics',
    'todos',
    'files',
    'buffers',
    'symbols'
  },
  todos = {
    initially_closed = true
  },
  update_interval = 1000
}
```
</details>

<details>
  <summary>Buffer sorting by name</summary>

![image](https://user-images.githubusercontent.com/58056722/154922670-66bf28cc-cef6-4384-a49e-f6957bae2a5b.jpeg)
</details>

<details>
  <summary>Triggering TODO sorting issue</summary>

https://user-images.githubusercontent.com/58056722/154922296-1e9e76b2-8093-44c5-bb00-d66b8cbbeb3f.mov
</details>
