### ISSUE TITLE
Close confirmation dialog closes neovim regardless of answer

### ISSUE THREAD

**Issue by SolarLiner** [sidebar-nvim/sidebar.nvim#39]
**Describe the bug**
When closing the last non-sidebar pane, the plugin asks for confirmation whether the user wants to quit Neovim. Regardless of the answer given (`y<CR>`, `<CR>`/`n<CR>`,`<ESC>`), Neovim always force quits (discarding any unsaved buffers).

**To Reproduce**
1. Open sidebar
2. Close other non-sidebar windows
3. Decline closing Neovim when asked
4. Neovim gets closed anyway

**Expected behavior**
Trivially 🤓 , declining closing Neovim should be honored.

**Screenshots**

**Environment (please complete the following information):**
 - nvim version: **0.6.1**
 - sidebar setup: 
 ```lua
local sidebar = require("sidebar-nvim")
sidebar.setup({
    open = true,
    sections = { "files", "git", "todos", "diagnostics", "symbols" },
    section_separator = "> ===================",
})
```
 - dotfiles (if any): Not applicable?

**Comment by GustavoKatel** [comment]
just pushed a fix to the `dev` branch, if all good I will merge to `main`
