### ISSUE TITLE
Empty lines after section_title should be configurable 

### ISSUE THREAD

**Issue by ray-x** [sidebar-nvim/sidebar.nvim#66]
**Is your feature request related to a problem? Please describe.**
The session area took too much space. Would be good allows a way I can remove the empty line after session title

**Describe the solution you'd like**
Only add empty line if it is configured. Or, we can do session_header = {'--------', 'git status'} so it will not show, or session_header = {'--------', 'git status',  '-------'} if I need an empty line or something else, e.g. another '-------',

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1681295/172986357-8bd3e613-4a32-49de-9b58-62fd34a082b5.png">

**Comment by GustavoKatel** [comment]
hi @ray-x 

you have two options to customize this:

1- In your setup you can pass a table to `section_separator`, like so:

```lua
sidebar.setup({
...
section_separator = { "-----" } -- default is { "", "-----", "" }
...
})
```

2- Another option is to pass a function (this way you can customize the separator for each section)

```lua
sidebar.setup({
...
section_separator = function(section, index) return { "-----" } end
...
})
```

More info here: https://github.com/sidebar-nvim/sidebar.nvim/blob/main/doc/general.md#options

**Comment by GustavoKatel** [comment]
🤔 giving this a second thought. You meant `section title` and not section separator! we can def make that happen

I will reopen this and work on it. Thanks for the suggestion @ray-x

**Comment by GustavoKatel** [comment]
done! It's in the `dev` branch

See `section_title_separator` here: https://github.com/sidebar-nvim/sidebar.nvim/blob/dev/doc/general.md#options
