### ISSUE TITLE
[Feature] add key binding to builtin sections

### ISSUE THREAD

**Issue by ray-x** [sidebar-nvim/sidebar.nvim#67]
**Is your feature request related to a problem? Please describe.**
e.g I want to add `a` in git section to add current file

**Describe the solution you'd like**
Allow { sections = {git = {bindings = {['a'] = function(line, pos) add_file(line) end}}}}

**Comment by GustavoKatel** [comment]
by "add current file" you mean call `git add`? If so, we already have a builtin key binding to do that. If you press `s` on a file in the sidebar git list it will call `git add <selected file>`.

if `s` isn't your liking you can change it, but note that right now if you want to customize a section keybinding you need to do some manual steps, but we're working to improve this.

you can do this:

```lua
local git_section = require("sidebar-nvim.builtin.git")
git_section.bindings["a"] = git_section.bindings["s"]
```

let me know if that works for you

**Comment by ray-x** [comment]
`s` works for me.
Thanks!
